[package]
name = "dps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
elasticsearch = "8.5.0-alpha.1"
# tokio = { version = "*", features = ["full"] }
serde_json = "1.0.91"
env_logger = "0.10.0"
thiserror = "1.0.38"